version: '3.6'

services:
    redis:
      image: 'redis'
      ports:
        - 6379:6379
      networks: 
        - local

    postgres:
      image: 'postgres'
      ports:
        - 5432:5432 
      environment:
        POSTGRES_PASSWORD: postgres  
        POSTGRES_DB: apiauth 
      networks: 
        - local

networks:
  local:
